import React from 'react'
import { ChangeEvent, useState } from 'react'
import { Button, TextField } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { createUserSchema } from '../utils/schema.util'
import { send } from './api/api'
import { useFormik } from 'formik'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import Link from 'next/link'

const Home: NextPage = () => {

  const formik = useFormik({
    initialValues: {
      name: '',
      cpf: '',
      alias: '',
      gender: '',
      phone: '',
      address: '',
      comments: '',
      profilePicture: ''
    },
    validationSchema: createUserSchema,
    onSubmit: (data) => {
      send(data)
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Services Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer/>

      <main className={styles.main}>
        <h2>Cadastro</h2>
        <form className={styles.form} onSubmit={formik.handleSubmit} >
            <div className={styles.grid}>

              <TextField
                className={styles.input}
                id="outlined-basic"
                name='name'
                label="name*"
                variant="outlined"
                value={formik.values.name}
                onChange={formik.handleChange}
                error={formik.touched.name && Boolean(formik.errors.name)}
                helperText={formik.touched.name && formik.errors.name}
              />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name='cpf'
                label="cpf*"
                variant="outlined"
                value={formik.values.cpf}
                onChange={formik.handleChange}
                />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name='alias'
                label="apelido"
                variant="outlined"
                value={formik.values.alias}
                onChange={formik.handleChange}
              />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name="gender"
                label="gênero"
                variant="outlined"
                value={formik.values.gender}
                onChange={formik.handleChange}
              />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name="phone"
                label="telefone"
                variant="outlined"
                value={formik.values.phone}
                onChange={formik.handleChange}
                />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name="address"
                label="endereço"
                variant="outlined"
                value={formik.values.address}
                onChange={formik.handleChange}
                />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name="comments"
                label="observações"
                variant="outlined"
                value={formik.values.comments}
                onChange={formik.handleChange}
                />
              <TextField
                className={styles.input}
                id="outlined-basic"
                name="profilePicture"
                label="foto de perfil"
                variant="outlined"
                value={formik.values.profilePicture}
                onChange={formik.handleChange}
              />

            </div>
          <p>Os campos com * são obrigatórios!</p>
          <Button className={styles.button} variant="contained" type='submit'>Enviar</Button>
          <Link href={`/users`}>
            <Button variant="contained" type='submit'>Veja os usuários</Button>
          </Link>
        </form>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/ericestevesmartins/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Desenvolvido por Eric Martins
        </a>
      </footer>
    </div>
  )
}

export default Home
